# Generated by Django 2.2.12 on 2022-10-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
